# Generated by Django 4.1.3 on 2022-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='.media/recipes/images/', verbose_name='Изображение рецепта'),
        ),
    ]
