# Generated by Django 4.1.3 on 2022-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания рецепта'),
        ),
    ]
